export { default as accountRoutes } from './account.routes';
export { default as establishmentRoutes } from './establishment.routes';
export { default as notificationRoutes } from './notification.routes';
export { default as paymentRoutes } from './payment.routes';
export { default as propertyRoutes } from './property.routes';
export { default as reservationRoutes } from './reservation.routes';
export { default as reviewRoutes } from './review.routes';
export { default as userRoutes } from './user.routes';
export { default as vtuRoutes } from './vtu.routes';
